### ISSUE TITLE
Error loading existing model through keras

### ISSUE THREAD

**Issue by girishnr1** [yoavram/DataSciPy#1]
Error loading existing model as part of transfer learning example:

model = keras.models.load_model('../data/keras_cnn_model.h5')

ValueError                                Traceback (most recent call last)
<ipython-input-15-5e350d7db5b3> in <module>
----> 1 model = keras.models.load_model('../data/keras_cnn_model.h5')

/Anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/models.py in load_model(filepath, custom_objects, compile)
    244       raise ValueError('No model found in config file.')
    245     model_config = json.loads(model_config.decode('utf-8'))
--> 246     model = model_from_config(model_config, custom_objects=custom_objects)
    247 
    248     # set weights

/Anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/models.py in model_from_config(config, custom_objects)
    322                     'Maybe you meant to use '
    323                     '`Sequential.from_config(config)`?')
--> 324   return layer_module.deserialize(config, custom_objects=custom_objects)

**Comment by yoavram** [comment]
Did you run the K_CNN notebook to create the model?

**Comment by girishnr1** [comment]
Yes.  K_CNN saved the model (keras_cnn_model.h5  ) under data folder.  
Seems like another person is having similar issue.

**Comment by yoavram** [comment]
OK. I also note from the error message that you use tensorflow.keras, is that right? Is that the way I did it (may very well be)?
Can you try to import keras directly instead of importing it from tensorflow?

**Comment by girishnr1** [comment]
This works! Thanks.
from keras.models import load_model
model = load_model('../data/keras_cnn_model.h5')

**Comment by yoavram** [comment]
So I'm not really sure what caused your problem, as the notebook uses `import keras` rather than `from tensorflow import keras`.
Can you explain so that I can fix the notebook?

**Comment by girishnr1** [comment]
It seems strange

Original code errors out.
   model = keras.models.load_model('../data/keras_cnn_model.h5') 

 244       raise ValueError('No model found in config file.')
    245     model_config = json.loads(model_config.decode('utf-8'))
--> 246     model = model_from_config(model_config, custom_objects=custom_objects)


New code: works fine.
   from keras.models import load_model
   model = load_model('../data/keras_cnn_model.h5')

**Comment by yoavram** [comment]
Can you please check how do you import keras?

**Comment by girishnr1** [comment]
Looks like it's from tensor flow.   
from tensorflow import keras

**Comment by girishnr1** [comment]
import keras outputs "Using TensorFlow backend."

**Comment by girishnr1** [comment]
On a seperate note,  I have created custom image train and test set (28x28).  Trying to train using transfer learning [ './data/keras_cnn_model.h5']  
 'fit'  is failing with the following error.    Any pointers?


ValueError: Error when checking target: expected dense_2 to have shape (10,) but got array with shape (8,)

**Comment by yoavram** [comment]
So the solution is to import keras directly. 
The output about the backend is standard. 

The error you now mention is about the shapes, probably the y you supplied to fit has the wrong shape, should be (-1,10)
